services:
  # Web Service
  - type: web
    name: therapy-companion
    env: python
    plan: free
    buildCommand: "chmod +x render-build.sh && ./render-build.sh && pip install -r requirements.txt"
    startCommand: "./startup.sh"
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "new_backend.py"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: APP_BASE_URL
        value: "https://therapy-companion.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString

  # Redis Service
  - type: redis
    name: therapy-companion-redis
    plan: free
    ipAllowList: []

  # Celery Worker
  - type: worker
    name: therapy-companion-celery
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "new_backend.py"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString

  # Celery Beat Scheduler
  - type: worker
    name: therapy-companion-celery-beat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A celery_app beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "new_backend.py"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString
