services:
  # Web Service only - database already exists
  - type: web
    name: therapy-companion
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./startup.sh"
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://therapy_user:vwzIok56kcQ4lulTQ93F1Imy4wfZO7vR@dpg-d1n4oifdiees73eobbng-a.oregon-postgres.render.com/therapy_companion"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "new_backend.py"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
