services:
  # Web Service - with WeasyPrint support
  - type: web
    name: therapy-companion
    runtime: docker
    plan: starter  # or 'standard' for paid tier
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: therapy-companion-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "new_backend.py"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: APP_BASE_URL
        value: "https://therapy-companion.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString

  # Redis Service
  - type: redis
    name: therapy-companion-redis
    plan: starter  # paid tier
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Celery Worker
  - type: worker
    name: therapy-companion-celery
    runtime: docker
    plan: starter  # paid tier
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A celery_app worker --loglevel=info --concurrency=2
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: therapy-companion-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "new_backend.py"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString

  # Celery Beat Scheduler
  - type: worker
    name: therapy-companion-celery-beat
    runtime: docker
    plan: starter  # paid tier
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A celery_app beat --loglevel=info
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: therapy-companion-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "new_backend.py"
      - key: REDIS_URL
        fromService:
          type: redis
          name: therapy-companion-redis
          property: connectionString

databases:
  - name: therapy-companion-db
    databaseName: therapy_companion
    user: therapy_user
    plan: starter  # paid tier
